config/routes.rb
Rails.application.routes.draw do
  root :to => "sessions#welcome", :id => '1'
  resources :parks do
    resources :comments
  end

  resources :dogs
  resources :users
  resources :sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar

  validates :name, presence: true
  validates :user, presence: true
  validates :bio, presence: true
  validates :avatar, presence: true

  def image_resize
    self.avatar.variant(resize: "250x250")
  end
end

app/models/park.rb
class Park < ApplicationRecord
    has_many :comments
    has_many :users, through: :comments

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :dogs
    has_many :comments
    has_many :parks, through: :comments

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?
    def current_user    
        @current_user = User.find_by(id: session[:user_id])  if session[:user_id]
    end
    def logged_in?
       
        !current_user.nil?  
    end
    def authorized
        redirect_to '/welcome' unless logged_in?
     end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_park
    #before_action :find_park, only: [:edit, :update, :destroy]
    def new 
        @comment = Comment.new
        @park = Park.find(params[:park_id])
    end 

    def create 
        @comment = Comment.new(comment_params)
        #associate a comment with the current park
        @comment.park_id = @park.id
        @comment.user_id = session[:user_id]

        if @comment.valid?
            @comment.save
            redirect_to @park
        else
            render :new
        end 
    end

    def edit
        #byebug
    end

    def update
        if @comment.update(comment_params)
            redirect_to @park
        else 
            render :edit
        end
    end 

    def destroy
        @comment.destroy
        redirect_to @park
    end 

private 
    def comment_params
        params.require(:comment).permit(:text)
    end

def find_park
    @park = Park.find(params[:park_id])
end

#finding the current park that the comment is associated with (park_id in database)
    def find_comment
        @comment = Comment.find(params[:id])
    end 

end 

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    def index
        @dogs = Dog.all
    end
    def show
        @dog = Dog.find(params[:id])
    end
    def new 
        @dog = Dog.new
    end
    def create
        @dog = Dog.new(dog_params)
        @dog.user_id = session[:user_id]
        if @dog.valid?
            @dog.save
            redirect_to @dog
        else 
            redirect_to :new
        end
    end


    private
    def dog_params
        params.require(:dog).permit(:name, :avatar, :bio)
    end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
    
    def index
        @parks = Park.all
    end 

    
    def show
        @park = Park.find(params[:id])
        @picture = params[:id]
        @comment = Comment.new
    end 
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
       session[:user_id] = @user.id
       redirect_to '/parks'
    end
    
  end

  def welcome
  end
  def page_requires_login
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/welcome'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]
    def show
        @user = User.find(params[:id])
    end
    def new 
        @user = User.new
    end
    def create 
        @user = User.new(user_params)
        #store in lowercare to avoid duplcates
        @user.email.downcase!
        if @user.valid?
            @user.save
            flash[:notice] = "Account created successfully!"
            session[:user_id] = @user.id
            redirect_to @user
        else 
            flash.now.alert = "Oops, not successful! please ask your hooman to created an account for you and try again. "
            render '/welcome'
        end
    end

    private 
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_form.html.erb
<%# @park parameter is the current instance of the park %>
<%# second parameter is possible through associations.  park has many comments. building a comment from the park  %>

app/views/comments/new.html.erb
<div class="text-center">
<img class="img-fluid img-thumbnail" width="20% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/6051/screenshots/7779269/media/3e92a3efe674d3348c7ddc8b76fca084.png" />

<h1> Share your adventure </h1>
<%= form_for [@park, @comment] do |f|%>
<%= f.text_area :text %><br>
<%= f.submit %> 
<% end %>

</div>

app/views/dogs/index.html.erb
<html>
<div class="text-center">
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<br><br>
 <h1 class="mt-4">GET TO KNOW A DOG</h1>
 <h3>Click on the photo to read their bio</h3><br>
  <% @dogs.each do |f|%>
   <%=link_to image_tag(f.avatar, style: 'width: 25%'), dog_path(f) %>
<% end %>
 
</div>
</html>

app/views/dogs/new.html.erb
<div class="text-center">
<h1 class="display-1">ADD A NEW PUP</h1><br>
      <img class="img-fluid img-thumbnail" width="40% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/502620/screenshots/5397310/doggo_3d.gif" />


<%= form_with model: @dog do |f|%>
<label>Name: </label><br>
<%= f.text_field :name %><br>


<label>Bio: </label><br>
<%= f.text_area :bio %><br>

<label>Image: </label><br>
<%= f.file_field :avatar %><br>
<%= f.submit %>
<% end %>
</div>
</div>

app/views/dogs/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/blog-post.css" rel="stylesheet">

</head>

<div class="text-class">
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />



<body>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Hello <%= @dog.name %>!</h1>


<h3>Master:<%=link_to @dog.user.name, user_path(@dog.user) %></h3>


<div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <%= image_tag @dog.avatar, :size => "300x200" %>
                <div class="card-body">
<p class="card-text">
<%= @dog.bio %>
</p>
</div></div></div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="app/assets/stylesheets/application.scss">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <!-- Navbar brand -->
  <a class="navbar-brand" href="#">Austin Pawsome Adventures</a>

  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <% if current_user %>
        Logged in as <%=link_to current_user.name, user_path(current_user) %>
      </li>
      <li class="nav-item">
        <%= link_to "--------------Log out", session_path("current"), method: "delete"%>
        <% end %>

      </li>
      <li class="nav-item">
        <%= link_to "--------------All Dogs", dogs_path%>
      </li>
      <li class="nav-item">
        <%= link_to "--------------All Parks", parks_path%>
      </li>

        </ul>
        
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/parks/index.html.erb
<style>
body {
  background-image: url("https://myrealdomain.com/images/cactus-border-clipart-8.jpg");
  background-color: #CCCCCC;
}
</style>

<div class="text-center">
<h1 class="display-1">
  Best Dog Parks in Austin Texas!</h1>
  <h4>click on any park to choose your next adventure</h4>
 
<br>
<h4 class="display-4">
  <% @parks.each do |park| %>
      <%= link_to park.name, park_path(park.id) %> <br>
  <% end %>
 </h4>
 </div>

  

app/views/parks/show.html.erb
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />


<br><br><br>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7">
      <h3 class="display-1">
         <%= @park.name %><br></h3>
          <div style="font-size: 20px" class="lead">
     <span class="text-muted">
        <%= @park.location %><br>
     </span>
     
        <%= @park.description %>
        </div>
      </div>
      </div>
     
      <div class="col-md-5">
         <%= image_tag("#{@picture}.jpg", :size => "500x300") %> 
   </div>
   <button type="button" class="btn btn-info btn-lg btn-rounded text-lg">
<%= link_to "ADD COMMENT", new_park_comment_path(@park) %>
</button>

        <!-- Single Comment -->
       <h1 class="mt-4">comments: 
              </h1> 
     <%@comments = @park.comments %>
              <% @comments.each do |f|%>
        <div class="media mb-6">
          <img class="d-flex mr-3 rounded-circle" class="img-fluid img-thumbnail" width="7% \9;" src="https://cdn.dribbble.com/users/502620/screenshots/5397310/doggo_3d.gif" /> 
         <div style="font-size: 15px" class="media-body mt-2">
           
              <%= f.user.name%>:
              <%=f.text %>
              
        </div>
        </div>
       
<% end %>
       
           
    

app/views/users/index.html.erb
afgsdh

app/views/users/new.html.erb
<div class="text-center">
<img class="img-fluid img-thumbnail" width="20% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/6051/screenshots/7779269/media/3e92a3efe674d3348c7ddc8b76fca084.png" />
<br>
<h1>Create a Hooman Account</h1>

<%= form_with model: @user do |f|%>
<label>Name: </label><br>
<%= f.text_field :name %><br>
<label>Email: </label><br>
<%= f.text_field :email %><br>
<label>Password: </label><br>
<%= f.password_field :password %><br>

<%= f.submit %>
<% end %>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/blog-post.css" rel="stylesheet">

</head>


<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />
<img class="img-fluid" width="19% \9;" alt="Responsive image" src="https://cdn.dribbble.com/users/237814/screenshots/4387219/casper-avatars_drib.jpg" />



<body>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Hello <%= @user.name.capitalize %>!</h1>

<h3>Here are your Beloved Fur-Babies! Click on the photo to read their bio</h3><br>

<form action="/dogs/new" method="get">
  <button class="btn btn-info btn-lg btn-rounded text-lg">Add Another Dog</button>
</form><br>

        <!-- Preview Image -->
         <div class="text-center">
       
         
        <%@dogs = @user.dogs %>
        <% @dogs.each do |f|%>    
             
        <%=link_to image_tag(f.avatar, style: 'width: 45%'), dog_path(f.id) %>
        
        <% end %>
        
        <hr>
        </div>
        
        

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>